<?xml version="1.0"?>
<!--

Copyright (c) 2020, Botsync Pte. Ltd.
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the Botsync Pte. Ltd. nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

-->

<robot name="volta_robot" xmlns:xacro="https://ros.org/wiki/xacro">

    <xacro:macro name="camera_" params="frame:=camera topic:=camera info_topic:=camera_info update_rate:=50 intel_d435i_enabled:=true orbbec_astra_pro_enabled:=false robot_namespace:=/">

        <xacro:if value="${intel_d435i_enabled}">
          <!-- Camera link -->
          <link name="${frame}_front">
              <visual>
                  <origin xyz="0 0 -0.0125" rpy="0 0 0"/>
                  <geometry>
                      <mesh filename="package://descriptions/meshes/d435i.dae"/>
                  </geometry>
              </visual>
              <collision>
                  <origin xyz="0 0 -0.0125" rpy="0 0 0"/>
                  <geometry>
                      <mesh filename="package://descriptions/meshes/d435i.dae"/>
                  </geometry>
              </collision>
              <inertial>
                  <mass value="0.162"/>
                  <origin xyz="-0.003 0 ${0.0125-0.0125}" rpy="0 0 0"/>
                  <inertia ixx="0.00011" ixy="0.0" ixz="0.0" iyy="0.00005" iyz="0.0" izz="0.00011"/>
              </inertial>
          </link>
          <link name="${frame}_right">
            <visual>
                <origin xyz="0 0 -0.0125" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://descriptions/meshes/d435i.dae"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 -0.0125" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://descriptions/meshes/d435i.dae"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="0.162"/>
                <origin xyz="-0.003 0 ${0.0125-0.0125}" rpy="0 0 0"/>
                <inertia ixx="0.00011" ixy="0.0" ixz="0.0" iyy="0.00005" iyz="0.0" izz="0.00011"/>
            </inertial>
        </link>
        <link name="${frame}_left">
            <visual>
                <origin xyz="0 0 -0.0125" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://descriptions/meshes/d435i.dae"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 -0.0125" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://descriptions/meshes/d435i.dae"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="0.162"/>
                <origin xyz="-0.003 0 ${0.0125-0.0125}" rpy="0 0 0"/>
                <inertia ixx="0.00011" ixy="0.0" ixz="0.0" iyy="0.00005" iyz="0.0" izz="0.00011"/>
            </inertial>
        </link>
          <!-- Camera joint -->
        <joint name="base_to_camera_front" type="fixed">
            <parent link="base_link"/>
            <child link="${frame}_front"/>
            <origin xyz="${camera_joint_x} ${camera_joint_y} ${camera_joint_z + 0.0125}"/>
        </joint>
        <joint name="base_to_camera_right" type="fixed">
            <parent link="base_link"/>
            <child link="${frame}_right"/>
            <origin xyz="0.0 -0.2 ${camera_joint_z + 0.0125}" rpy="0 0 -1.5707"/>
        </joint>
        <joint name="base_to_camera_left" type="fixed">
            <parent link="base_link"/>
            <child link="${frame}_left"/>
            <origin xyz="0.0 0.2 ${camera_joint_z + 0.0125}" rpy="0 0 1.5707"/>
        </joint>
        </xacro:if>

        <xacro:if value="${orbbec_astra_pro_enabled}">
          <!-- Camera link -->
          <link name="${frame}">
              <visual>
                  <origin xyz="0 0 -0.0337" rpy="0 0 0"/>
                  <geometry>
                      <mesh filename="package://descriptions/meshes/astra.dae"/>
                  </geometry>
              </visual>
              <collision>
                  <origin xyz="0 0 -0.0337" rpy="0 0 0"/>
                  <geometry>
                      <mesh filename="package://descriptions/meshes/astra.dae"/>
                  </geometry>
              </collision>
              <inertial>
                  <mass value="0.3"/>
                  <origin xyz="-0.004 0 ${0.028 - 0.0337}" rpy="0 0 0"/>
                  <inertia ixx="0.0002" ixy="0.0" ixz="0.0" iyy="0.0003" iyz="0.0" izz="0.0003"/>
              </inertial>
          </link>
          <!-- Camera joint -->
          <joint name="base_to_camera" type="fixed">
              <parent link="base_link"/>
              <child link="${frame}"/>
              <origin xyz="${camera_joint_x} ${camera_joint_y} ${camera_joint_z + 0.0337}"/>
          </joint>
        </xacro:if>

        <gazebo reference="${frame}_front">
            <sensor name="camera" type="depth">
                <update_rate>20</update_rate>
                <camera>
                <horizontal_fov>1.75</horizontal_fov>
                <!-- <horizontal_fov>1.047198</horizontal_fov> -->
                <image>
                    <width>640</width>
                    <height>480</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.05</near>
                    <far>3</far>
                </clip>
                </camera>
                <plugin name="camera_controller" filename="libgazebo_ros_openni_kinect.so">
                <baseline>0.2</baseline>
                <alwaysOn>true</alwaysOn>
                <updateRate>1.0</updateRate>
                <cameraName>${frame}_front_ir</cameraName>
                <imageTopicName>${frame}_front/color/image_raw</imageTopicName>
                <cameraInfoTopicName>${frame}_front/color/camera_info</cameraInfoTopicName>
                <depthImageTopicName>${frame}_front/depth/image_raw</depthImageTopicName>
                <depthImageInfoTopicName>${frame}_front/depth/camera_info</depthImageInfoTopicName>
                <pointCloudTopicName>${frame}_front/depth/points</pointCloudTopicName>
                <frameName>${frame}_front</frameName>
                <pointCloudCutoff>0.5</pointCloudCutoff>
                <pointCloudCutoffMax>3.0</pointCloudCutoffMax>
                <distortionK1>0.00000001</distortionK1>
                <distortionK2>0.00000001</distortionK2>
                <distortionK3>0.00000001</distortionK3>
                <distortionT1>0.00000001</distortionT1>
                <distortionT2>0.00000001</distortionT2>
                <CxPrime>0</CxPrime>
                <Cx>0</Cx>
                <Cy>0</Cy>
                <focalLength>0</focalLength>
                <hackBaseline>0</hackBaseline>
                </plugin>
            </sensor>
        </gazebo>
        <gazebo reference="${frame}_right">
            <sensor name="camera" type="depth">
                <update_rate>20</update_rate>
                <camera>
                <horizontal_fov>1.75</horizontal_fov>
                <image>
                    <width>640</width>
                    <height>480</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.05</near>
                    <far>3</far>
                </clip>
                </camera>
                <plugin name="camera_controller" filename="libgazebo_ros_openni_kinect.so">
                <baseline>0.2</baseline>
                <alwaysOn>true</alwaysOn>
                <updateRate>1.0</updateRate>
                <cameraName>${frame}_right_ir</cameraName>
                <imageTopicName>${frame}_right/color/image_raw</imageTopicName>
                <cameraInfoTopicName>${frame}_right/color/camera_info</cameraInfoTopicName>
                <depthImageTopicName>${frame}_right/depth/image_raw</depthImageTopicName>
                <depthImageInfoTopicName>${frame}_right/depth/camera_info</depthImageInfoTopicName>
                <pointCloudTopicName>${frame}_right/depth/points</pointCloudTopicName>
                <frameName>${frame}_right</frameName>
                <pointCloudCutoff>0.5</pointCloudCutoff>
                <pointCloudCutoffMax>3.0</pointCloudCutoffMax>
                <distortionK1>0.00000001</distortionK1>
                <distortionK2>0.00000001</distortionK2>
                <distortionK3>0.00000001</distortionK3>
                <distortionT1>0.00000001</distortionT1>
                <distortionT2>0.00000001</distortionT2>
                <CxPrime>0</CxPrime>
                <Cx>0</Cx>
                <Cy>0</Cy>
                <focalLength>0</focalLength>
                <hackBaseline>0</hackBaseline>
                </plugin>
            </sensor>
        </gazebo>
        <gazebo reference="${frame}_left">
            <sensor name="camera" type="depth">
                <update_rate>20</update_rate>
                <camera>
                <horizontal_fov>1.75</horizontal_fov>
                <image>
                    <width>640</width>
                    <height>480</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.05</near>
                    <far>3</far>
                </clip>
                </camera>
                <plugin name="camera_controller" filename="libgazebo_ros_openni_kinect.so">
                <baseline>0.2</baseline>
                <alwaysOn>true</alwaysOn>
                <updateRate>1.0</updateRate>
                <cameraName>${frame}_left_ir</cameraName>
                <imageTopicName>${frame}_left/color/image_raw</imageTopicName>
                <cameraInfoTopicName>${frame}_left/color/camera_info</cameraInfoTopicName>
                <depthImageTopicName>${frame}_left/depth/image_raw</depthImageTopicName>
                <depthImageInfoTopicName>${frame}_left/depth/camera_info</depthImageInfoTopicName>
                <pointCloudTopicName>${frame}_left/depth/points</pointCloudTopicName>
                <frameName>${frame}_left</frameName>
                <pointCloudCutoff>0.5</pointCloudCutoff>
                <pointCloudCutoffMax>3.0</pointCloudCutoffMax>
                <distortionK1>0.00000001</distortionK1>
                <distortionK2>0.00000001</distortionK2>
                <distortionK3>0.00000001</distortionK3>
                <distortionT1>0.00000001</distortionT1>
                <distortionT2>0.00000001</distortionT2>
                <CxPrime>0</CxPrime>
                <Cx>0</Cx>
                <Cy>0</Cy>
                <focalLength>0</focalLength>
                <hackBaseline>0</hackBaseline>
                </plugin>
            </sensor>
        </gazebo>
    </xacro:macro>
</robot>
